### ISSUE TITLE
Disable wheel zoom

### ISSUE THREAD

**Issue by cfreear** [svgdotjs/svg.panzoom.js#12]
We currently use this plugin and svg.js on a page with a full width SVG (contents are generated from database values so width is unknown) and the mousewheel zoom blocks the natural page scroll. We plan on implementing zoom buttons using the ``.zoom()`` method so it would be good if there was an option to disable mouse wheel zooming. Willing to submit a PR if this would be of interest.

**Comment by Fuzzyma** [comment]
Thats a good idea. Maybe we could need the same for panning.

**Comment by cfreear** [comment]
PR submitted: #15

**Comment by kevindecapite** [comment]
Is this option in the codebase? I don't see it documented, but there's a PR for it.

**Comment by Fuzzyma** [comment]
When the PR is still open it's most likely not in the code base :). Maybe it was forgotten. So much stuff to do. In the meantime you can use the branch from the PR if you need that feature

**Comment by MusicCorner** [comment]
> We currently use this plugin and svg.js on a page with a full width SVG (contents are generated from database values so width is unknown) and the mousewheel zoom blocks the natural page scroll. We plan on implementing zoom buttons using the `.zoom()` method so it would be good if there was an option to disable mouse wheel zooming. Willing to submit a PR if this would be of interest.

if you want to off mousewheel zooming, just make zoomFactor = 0.00000001))

draw.panZoom({zoomMin: 0.5, zoomMax: 10, zoomFactor: 0.00000001});

**Comment by Fuzzyma** [comment]
closed with #15
