### ISSUE TITLE
enabled / disabled pan zoom by controls

### ISSUE THREAD

**Issue by MrLugh** [svgdotjs/svg.panzoom.js#17]
Guys, once i run elementUi.panZoom({zoomMin:0.01}) i would like to cancel panZoom in the future but i can't.
I tried $(elementUi.node).unbind('pinchZoomStart'); elementUi.off('pinchZoomStart') but panZoom continue working

**Comment by Fuzzyma** [comment]
try the fix-min-max-zoom branch. theer you can just call `el.panZoom(false)`

**Comment by MrLugh** [comment]
Thanks! I will try it.
Can i install it with bower?

**Comment by Tecuion** [comment]
Guys, it doesn't work when I call rect.panZoom(false) to disable the panZoom. Is anybody fixed it? thanks a lot.

**Comment by Fuzzyma** [comment]
Are you using the latest master? Why would you use panzoom on a rect element anyway? :D
