### ISSUE TITLE
incorrect center point

### ISSUE THREAD

**Issue by dasDaniel** [svgdotjs/svg.panzoom.js#19]
Is anyone else finding that the bounds of the zoom are not centered around the provided coordinates?

I create a rectangle, find the centre using bounds and pass that to panzoom
the center point is highlighted using a small square

```
draw = SVG('svg').size(window.innerWidth, window.innerHeight)
draw.rect(100,100).fill('rgba(256, 256, 180, 0.1)')
var bounds = draw.bbox()
draw.panZoom({zoomMin: 0.3, zoomMax: 3})
draw.rect(bounds.width, bounds.height).fill('rgba(256, 0, 180, 0.1)').addClass('box').move(bounds.x, bounds.y)
draw.rect(4,4).fill('rgba(256, 0, 180, 1)').addClass('box').move(bounds.cx-2, bounds.cy-2)
var z = draw.zoom(0.3).animate().zoom(2, {x:bounds.cx, y: bounds.cy})
```

as I change the rectangle size, the amount the center is off changes. when I match the window width and height, it becomes centered.

I'm thinking this part of the code in svg.panzoom may be missing some additional translation
https://github.com/svgdotjs/svg.panzoom.js/blob/master/src/svg.panzoom.js#L187

**Comment by Fuzzyma** [comment]
You habe to pass the point in the coordinate system of the element itself. So in case you already set a viewbox and this viewbox has any zoom or pan just passing your point won't do what you want. 
I tested the functionality of this plugin deeply and didn't have your issues anywhere. 

E.g. Try the zoom when scrolling with your mouse. The element is always zoomed into the point the mouse is on. You can easily test this by pointing at something and zoom in.

**Comment by dasDaniel** [comment]
Thanks Fuzzyma,

Shortly after posting it I realized what the issue was. The zoom is using the point as a reference to zoom around, as advertised. I was expecting it to center around that point.

Is there a way to center the viewbox around a point that would work with the animation?

**Comment by Fuzzyma** [comment]
No not in this plugin. However you can always animate the viewbox yourself. As you already said: it's a scaling transformation and a translation. 
So it's only a bit of math. If you figured this out I can help you to do that in clean code with svg.js

**Comment by dasDaniel** [comment]
I've found this to work pretty close

```
    var center =  new SVG.Point(width/2 / zoomX + v.x, height/2 / zoomY + v.y)
    point = point || center

    var box = new SVG.Box(v)
      .transform(new SVG.Matrix()
        .translate(point.x - center.x, point.y - center.y)
        .scale(zoomAmount, point.x, point.y)
      )
```

I think for the time being I may just keep that as part of the plugin and change function name to zoomTo
