### ISSUE TITLE
Unused variable dirtyViewbox

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.panzoom.js#2]
[`dirtyViewbox`](
https://github.com/svgdotjs/svg.panzoom.js/blob/master/svg.panzoom.js#L17) appears to be unused.

**Comment by Fuzzyma** [comment]
oh yes - I tested two approaches (basically debouncing the move event) and thats left from it

**Comment by dotnetCarpenter** [comment]
`dirtyViewbox` could be useful to use to get the zoom level, since `viewbox().zoom` does not work.

In `panZoom`, we could do

```js
var zoom = function(ev) {
  ev.preventDefault()

  var zoomAmount = ev.deltaY/Math.abs(ev.deltaY) * zoomFactor + 1

  var p = this.point(ev.clientX, ev.clientY)
  var b = new SVG.Box(this.viewbox()).transform(new SVG.Matrix().scale(zoomAmount, p.x, p.y))

  this.viewbox(b)
  this.fire('zoom', { zoomAmount: dirtyViewbox.width / b.width })
}
```

**Comment by Fuzzyma** [comment]
why would you pass `dirtyViewbox.width / b.width` to `zoomAmount`? Its just the ratio. The actual `zoomAmount` **IS** `zoomAmount` :D

**Comment by dotnetCarpenter** [comment]
`zoomAmount` is pretty much a constant, **0.97** for zooming in and **1.03** for zooming out. The numbers doesn't change according to how much you have zoomed in or out.

`dirtyViewbox.width / b.width` or `dirtyViewbox.height / b.height` gives you that. Perhaps the name should be *zoomLevel*.

Maybe an even better solution is to just fire an event and then fix `viewbox().zoom` in SVG.js.

**Comment by Fuzzyma** [comment]
In svg.ja v3 there won't be any zoom on viewbox anymore anyway because it's all just box. I never found this zoom property pretty useful and it's calculation was messy. If you need a zoom level you just do viewbox divided by size of the svg and you are done. No need to get fancy. 

However there is a valid point with firing an event there. Anyway I am not sure how the zoom level will help you much because it is not the ratio of size to viewbox but the ratio of old viewbox to new viewbox and that's very unintiutive

**Comment by wout** [comment]
Just to chime in here on the zoom property. For me, it's been a very useful feature in the past. I used it a lot. Maybe we can add it as a method on `SVG.ViewBox`. However, we'll have to find a way to implement this properly. But this is probably not the right place to discuss this.

**Comment by dotnetCarpenter** [comment]
I think the `.zoom` property will come in handy for implementing a `<range>` element that controls the size of SVG containers.  But I'll need to play a little more with this...

But I already made some small adjustments to svg.panzoom.js. I'll create a PR with my changes, so we can discuss them there.
