### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by jshailes** [svgdotjs/svg.panzoom.js#20]
It seems this code works great on Android devices, panning and zooming by using 2 fingers on the screen. On the iPad however this doesn't seem to work. Is this to be expected and if so are there any plans to provide iPad support in the near future?

**Comment by Fuzzyma** [comment]
I simply have no iPad to test with :/

**Comment by jshailes** [comment]
I was in the same boat until yesterday when it was reported the site didn't work on one. I'll have a go at debugging and try to figure out what's going wrong.

**Comment by Fuzzyma** [comment]
I think this comes from different api in iPad and Android or Safari and Chrome.
The touches are saved in different proporties. I am just not aware which ones

**Comment by sudodoki** [comment]
not sure about ipad, but with iphone I see that pinch is working and pan is not because of `if(lastTouches.length < 2) return` check in `pinchZoomStart` - it'll be the same event for pan / zoom but distinction should be made based on length of `touches`.

**Comment by Fuzzyma** [comment]
Panning works with 2 fingers. Did you try this?

**Comment by sudodoki** [comment]
@Fuzzyma oh gosh, never thought of it 😅 Yeah, it seems to work.
Also, some ugly fix I did in regards to handling single finger panning, which might be something I'll need to run with, if I don't convince people 2 fingers is exactly how many you need to pan image :) 
https://gist.github.com/sudodoki/4a5c1b7c76a307de435bad0597c8d739 - one issue with this approach is handling of initial touch, when you try to pinch and accidentally one finger gets to surface first and unsubscribes from pinching, as it's handling panning already, which is quite common, it seems.
Thanks for quick response and for this library for saving a ton of time! 👍

**Comment by Fuzzyma** [comment]
Mh Jeah panning stops when one finger leaves the surface. Which means when you have 3 fingers on it and you remove the third one it will stop. Actually that's a bug. We should check how much fingers are still there. However I think we get a problem when the first or second finger is removed because the touches-array shifts by one and that means coordinates gets switched which can lead to really weird behavior
