### ISSUE TITLE
zoom info is wrong when zooming out

### ISSUE THREAD

**Issue by Salamek** [svgdotjs/svg.panzoom.js#22]
Hi, i have this code:

```javascript
svg = SVG('svg').size('100%', '100%').panZoom({panMouse: 2, zoomFactor: 0.03, zoomMin: 0.5, zoomMax: 20});
svg.on('zoom', function(ev) {
    console.log(svg.zoom());
});
```

When i zoom in i get data from svg.zoom() like this:
```
1.0300000016911641
1.0599999740677215
1.089999925549374
1.1199998940773055
1.1499998489445757
1.1799998532704519
1.2099998871550262 //Here i stopped zooming in
```
And that looks OK, but when i zoom out i get this:
```
1.2399998435183597  //Here i started zooming out, this should be ~1.17999991514276
1.2099998888721086
1.17999991514276
```

SVG actualy zooms out properly but zoom info is incorrect and it is like 2 steps behind

**Comment by Fuzzyma** [comment]
Thats odd. We use the zoom info ourselves to zoom correctly so this is indeed mysterious.

nvm, i found the problem. The event is fired BEFORE the new zoom is applied. So you read the old value while a new is set. So you actually zoomed into 1.2399998435183597. So its always 1 step behind. 
The simple reason is: We want to give the user the possibility to cancel the zoom by calling `e.preventDefault()`. So the event is fired before the zoom is applied. We should pass the zoomLvl as event details so user know what will be the result of this zoom

**Comment by Salamek** [comment]
@Fuzzyma yea adding zoom info into event data is good idea (actualy i did it in my code, but passing zoom value to event did not fixed a issue for me... i think...)

**Comment by Fuzzyma** [comment]
What is your usecase?

**Comment by Salamek** [comment]
@Fuzzyma When i pass zoom to event data (No other code changes, i have same results):

```javascript
console.log(svg.zoom(), ev.detail.zoom);
```

```
1.0300000005189427 1.0300000005189427
1.059999983825684 1.059999983825684
1.0899999594789196 1.0899999594789196
1.1199999703346117 1.1199999703346117
1.1499999279601947 1.1499999279601947
1.1799999411799356 1.1799999411799356
1.2099999890266275 1.2099999890266275 //Here i stopped zooming in
1.2399999707261578 1.2399999707261578 // Here i started zooming out
1.2099999890266275 1.2099999890266275
1.1799999448995322 1.1799999448995322
1.1499999314930633 1.1499999314930633
1.1199999703346117 1.1199999703346117
```

This happends in Chromium 60.0.3112.113 Linux x86_64

I use svg.js to create simple SVG editor so i use like 80% of svg.js plugins, but this issue have nothing to do with my code, i called ```return;``` right after code sample i posted in issue description.

**Comment by Fuzzyma** [comment]
Thats because the correct "future" zoom is `zoom * zoomAmount`

**Comment by Salamek** [comment]
@Fuzzyma it is still doing weird stuff :-D I dont have much time to play with it right now... i need to get some sleep, sorry...

**Comment by Salamek** [comment]
@Fuzzyma this is just not fixing anything... number is differend and still wrong...

Ah correct variable i needed is level not zoom, when i pass level to zoom event and use it to scale my grid, everything works ok... finaly

https://github.com/Salamek/svg.panzoom.js/commit/53e4238f873120492305fa3057a14563d7a70707

IDK where to get level in pinchZoom function, so no PR yet...

**Comment by Fuzzyma** [comment]
So the trick is to get the zoom after it is actually set. The event however fires before it is set. Thats why you have to use `setImmediate()` or `setTimeout()` to execute the code in the event handler after the current chain
