### ISSUE TITLE
panzoom mouseup with zoom offset

### ISSUE THREAD

**Issue by Nogbit** [svgdotjs/svg.panzoom.js#25]
There is a lot of info in the zoom and panEnd events which is great.  But what I need to do is place a rect in the correct location on top of a zoomed in `pattern` with the zoom level offsetting the xy location of the rect.

Below is my current code and the before and after zoom of the top left of the browser.  For example, a mouseup at 20,20 in the first screenshot (no zoom) is a new rect to be placed at that location.  But in the second screenshot the rect needs to be placed at 20,20 + zoomoffset.  Let me know if there is a best practice or something existing in the API for this before I start hacking up some potential solutions.  If it's as simple as multiplying by `draw.viewbox().zoom` that will do. Thanks.

```JavaScript
<div id="drawing"></div>
<script>
    var size = {
      x: window.innerWidth || document.body.clientWidth,
      y: window.innerHeight || document.body.clientHeight
    }
    var draw = SVG('drawing').size(size.x, size.y).panZoom({
      zoomMin: 1, 
      zoomMax: 5,
      zoomFactor: .5
    })
    var rect = draw.rect(size.x, size.y)

    var pattern = draw.pattern(10, 60, function(add) {
      item = add.rect(10,60).fill('#141b26')
      add.rect(9,60).fill('#dc3545')
    })

    rect.attr({ fill: pattern })
        
    draw.on('zoom', function(ev) {
      console.log(ev.detail)
      console.log(draw.viewbox().zoom)
    })    

    draw.on('panEnd', function(ev) {
      console.log(ev.detail.event)
    }) 
</script>
```
![capture](https://user-images.githubusercontent.com/5131608/32148347-d846ab28-bcb2-11e7-8347-5685da27051a.PNG)
![capture2](https://user-images.githubusercontent.com/5131608/32148348-d85c64ea-bcb2-11e7-8a56-50e0686311b6.PNG)

**Comment by Fuzzyma** [comment]
`zoom()` will give you the factor you want. Please try it and report back!

**Comment by Nogbit** [comment]
All set, the following code works, it takes into account any panning the user may have done as well.

```JavaScript
    draw.on('panEnd', function(ev) {
      var data = ev.detail.event;
      var box  = draw.viewbox();
      var zoom = box.zoom;
      var x    = data.clientX;
      var y    = data.clientY;     
      
      if (zoom > 1) {
        x = x / zoom
        y = y / zoom
      }
      x += box.x
      y += box.y
      
      var rect = draw.rect(10, 10).fill('#000000').move(x, y);
    }) 
```
