### ISSUE TITLE
panEnd fires when panning does not occur

### ISSUE THREAD

**Issue by Nogbit** [svgdotjs/svg.panzoom.js#26]
I would expect panEnd to fire only if some actual panning took place, right now it fires on every mouseup making it difficult to do something different for mouseup.

**Comment by Fuzzyma** [comment]
https://github.com/svgdotjs/svg.draggable.js/issues/69

**Comment by Nogbit** [comment]
Thanks, just came up with a solution that was similar to the links there.  With the SVG `mousemove` event I set a `lastMouseMove = Date.now()` and then compare the delta in my SVG mouseup/panEnd/click events as needed.
