### ISSUE TITLE
Pan to coordinates

### ISSUE THREAD

**Issue by sefaYavuz** [svgdotjs/svg.panzoom.js#28]
Currently it is only possible to zoom in to the given coordinates. When the max zoom level has been reached you will not be able to move to another set of coordinates.

Can we have a 'Pan to coordinates' method which will add the ability to move to the given coordinates?

Something very similar to the `.zoom()` method? Something in the way of `.pan(point)`.

**Comment by Fuzzyma** [comment]
It's not likely that this will be implemented very soon. In the meantime you might want to code it for yourself. You can animate viewboxes.

Get the current zoom with `zoom()` and calculate where you want to be. You can then just call `canvas.animate().viewbox(newCoords) and it will animate for you. Ofc that also works without animation.

Panning is nothing else then moving the viewbox. You can even get fancy and translate the viewbox by an amount with 

```js
newCoords = canvas.viewbox().transform(new SVG.Matrix().translate(x, y))

canvas.viewbox(newCoords)
```

**Comment by sefaYavuz** [comment]
@Fuzzyma thanks for your reply! 

I already implemented something like you've described. But it would be awesome if the functionality came out of the box. Until then my implementation will do 👍

**Comment by Fuzzyma** [comment]
When you feel confident you can create a PR with your solution. I will certainly review it and can help when required.
