### ISSUE TITLE
Instead of a fixed step per scroll wheel turn we should use a percentage value

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.panzoom.js#29]
This is a bit weird to explain so please bare with me...

Right now when we use the scrollWheel what basically happens is that the SVG scale increases/decreases by a fixed amount (zoomFactor).

A better usability option seems to be using a 'multiplication factor'. This is inspired by another project, [svg-pan-zoom](https://github.com/ariutta/svg-pan-zoom) which does a very similar thing. 

This approach improves the usability because when you are zooming in if you use a fixed step you need to scroll a lot to really zoom in on what you want. By using a multiplication factor you "zoom more " as you are zooming in and "zoom less" when you are zooming out.

In my example I want to zoom from 0.5 to 10 with a zoomFactor of 0.2. You can check my example with the multiplication factor here: https://jsfiddle.net/95msu3jf/8/ 
Only change was `var lvl = Math.pow(1 + options.zoomFactor, (-1) * ev.deltaY / 100) * this.zoom()`

You can compare it with the original svg.panzoom.js code here: https://jsfiddle.net/95msu3jf/9/

Try these examples and specially zooming in. You can see in the original it's very annoying to get to zoom 10 as you need to scroll a lot. Yes, you can increase the zoomFactor so this is faster but then you lose a bit more control when you zoom out specially from 1 to 0.5. 

I think using a multiplication factor improves the usability a lot but I welcome your feedback and if I should do a PR for this.

**Comment by Fuzzyma** [comment]
I agree :D. However the api `zoom(level, point)` should stay. Only the calculation to which level to zoom next should be refined. But I see you did it like that.

Jeah fire up that PR :D

**Comment by pjfsilva** [comment]
Yes this only affects the scrollWheel zoom. With this change the zoomFactor config probably should also change name/description. The mentioned plugin calls it 'zoomScaleSensitivity'. 

What do you think? A good suggestion for a new name for it or we just change the description of it in the docs to reflect this is not 'how much is zoomed' but the factor by which it's zoomed?

**Comment by Fuzzyma** [comment]
I think its not worth breaking the api so I would stay with what it is for now and maybe change it, when we jump onto the next major version (which will probably be never^^)

**Comment by pjfsilva** [comment]
this change also slightly breaks backwards compatibility because 1 wheel scroll will zoomIn/out different values than before. I think that is OK and not a huge problem but what do you think?

**Comment by Fuzzyma** [comment]
hm maybe you are right and we should bump the major version. However I really would like to have the area constraint feature in the next major version (#14). I guess you did something there already, right? :D
