### ISSUE TITLE
pinchZoomStart not trggering

### ISSUE THREAD

**Issue by nkpdn** [svgdotjs/svg.panzoom.js#32]
draw.on('pinchZoomStart', function(ev) {
	console.log("stopped")
    ev.preventDefault()
})
 function  not triggering when we zoom.

**Comment by nkpdn** [comment]
and pinchZoomEnd

**Comment by Fuzzyma** [comment]
Are you on a smartphone or on a desktop?

**Comment by nkpdn** [comment]
laptop/desktop

**Comment by Fuzzyma** [comment]
pinchZoom is for 2 finger zoom and the event only triggers for that as far as i know

**Comment by Fuzzyma** [comment]
you can use the normal `zoom` event if you dont want the zoom to be executed

**Comment by nkpdn** [comment]
Thank you, could u please share the info about the issue #33 ?

**Comment by Fuzzyma** [comment]
What do you mean with share?

**Comment by Rubinhuang9239** [comment]
Yep, I can confirm the issue with `pinchZoomStart/End` events mentioned by @nkpdn, with ver. 2.0.3, also tested `zoom` event, which is working fine here.
