### ISSUE TITLE
disable pan and zoom

### ISSUE THREAD

**Issue by nkpdn** [svgdotjs/svg.panzoom.js#33]
el.panZoom(false) not disabling pan, it disables only zoom functionality

**Comment by nkpdn** [comment]
For particular functionality I need to disable pan.

**Comment by Fuzzyma** [comment]
Please create a jsfiddle showing your issue. I looked into the code and cannot find a way this issue can happen

**Comment by nkpdn** [comment]
https://jsfiddle.net/nkpd/pqa97L1m/24/

Here is the example,
if I call "draw.panZoom(false)" in line number 34(in setTime out function) it will works , but when I call in line number 15( i.e on panEnd function) it will not disable pan.

**Comment by Fuzzyma** [comment]
https://github.com/svgdotjs/svg.panzoom.js/blob/master/src/svg.panzoom.js#L137

Move that line down so it sits at the end of the body of the function. It should work now. Please report back.

**Comment by nkpdn** [comment]
Thank you.

**Comment by nkpdn** [comment]
But this is not working

**Comment by Fuzzyma** [comment]
Just tried it, it worked

**Comment by nkpdn** [comment]
Yup, its working. Thank you and I have one more question -> How enable any one functionality like enable only zooming not panning.?

**Comment by Fuzzyma** [comment]
There is no function like this atm. You would need to register or unregister the events yourself

**Comment by nkpdn** [comment]
Thanks a lot.

**Comment by Fuzzyma** [comment]
Feel free to make this little change a PR. I think its useful for other peoples, too
