### ISSUE TITLE
Reset the pan original before pan starts

### ISSUE THREAD

**Issue by cbarlow1993** [svgdotjs/svg.panzoom.js#35]
Is it possible to reset the pan programtically? i.e. With a reset button, I want to zoom to 1 and go back to original viewbox. 

I'm fairly new to this and running out of google search ideas. This feature would be great if not already implemented!

**Comment by Fuzzyma** [comment]
Nothing stops you from just setting the view box directly to the value you want. There is a handy `viewbox` method for that
