### ISSUE TITLE
How to use panzoom.js without npm

### ISSUE THREAD

**Issue by iapyeh** [svgdotjs/svg.panzoom.js#38]
Hi, do you plan to have a non-npm version of the Panzoom.js, just like the svg.js?
By simply putting  <script src="svg.js"> alone with <script src="panzoom.js"> and it works.

**Comment by Fuzzyma** [comment]
The svg.js v2 compatible version is in the dist folder. The new version which is v3 compatible has the bundle uploaded as zip at the release page.

**Comment by iapyeh** [comment]
Thank you ver much. I found it here [ariutta/svg-pan-zoom](https://github.com/ariutta/svg-pan-zoom)
