### ISSUE TITLE
viewbox width/height 0 ?

### ISSUE THREAD

**Issue by HelloYie** [svgdotjs/svg.panzoom.js#40]
Hello, when I use `svg.panzoom.js`,  I got svg `viewbox` attribute 0, 0. For example: `viewbox=281.8125 251.90625 0 0`. So the svg element is not visible in any case. 

* @svgdotjs/svg.js@v3.0.12
* @svgdotjs/svg.panzoom.js@2.0.2

my code:

```
import SVG from '@svgdotjs/svg.js/src/svg'
import '@svgdotjs/svg.filter.js'
import '@svgdotjs/svg.panzoom.js

SVG()
  .addTo('#graph')
  .size(800, 800)
  .panZoom({ zoomMin: 0.5, zoomMax: 20 });

```
![image](https://user-images.githubusercontent.com/5723225/54477525-acc34d80-4843-11e9-8675-0bc89f811320.png)

**Comment by Fuzzyma** [comment]
Create a jsfiddle with the issue please

**Comment by HelloYie** [comment]
Hello @Fuzzyma ,  I create a pen.

https://codepen.io/xiao17/pen/jJxpRz?editors=1010

**Comment by Fuzzyma** [comment]
Fixed it for you: https://codepen.io/fuzzyma/pen/ywjRRV?editors=1010

Zoom is no more than a ration from size to viewbox. When you set no viewbox on the element, panzoom uses 0 as size of the viewbox (because thats returned from the viewbox() getter).

So - Just make sure to set a viewbox

**Comment by HelloYie** [comment]
Got it!  Thanks a lot.

**Comment by jonenst** [comment]
Hi, got here for the same problem. The solution fixes the problem.
I suggest to add the call to .viewbox() to the readme available at https://github.com/svgdotjs/svg.panzoom.js/

**Comment by Fuzzyma** [comment]
feel free to add it!
