### ISSUE TITLE
Elements disappear when panning or zooming

### ISSUE THREAD

**Issue by bptarpley** [svgdotjs/svg.panzoom.js#41]
I'm very excited about the svg.js library and these awesome plugins. Thank you for this work. I'm having an issue, however, with this plugin, which is that while I can initiate the root SVG element and draw an image with 100% height and width, as soon as I try to pan or zoom the image disappears entirely. Here's how I have things setup--apologies if I'm missing something obvious:

```
<div id="delineator" class="h-100"></div>

<script src="js/jquery-3.3.1.min.js"></script>
<script src="node_modules/@svgdotjs/svg.js/dist/svg.js"></script><!-- 3.0.12 /-->
<script src="node_modules/@svgdotjs/svg.panzoom.js/dist/svg.panzoom.js"></script><!-- 2.0.2 /-->
<script type="application/javascript">
            var delineate;
            var canvas;
            var image;

            $(document).ready(function() {
                delineate = SVG().addTo('#delineator')
                    .size("100%", "100%")
                    .attr('id', 'svg-delineator')
                    .panZoom({panMouse: 2, zoomFactor: 0.03, zoomMin: 0.5, zoomMax: 20});
                canvas = delineate.group().attr('class', 'delineator-canvas');
                image = canvas.image('img/newspaper.jpeg');
            });
```

I've tried adding the image directly to the root SVG element instead of putting it inside a group element first. I've tried leaving the default options for .panZoom. I've tried setting an explicit height and width for the SVG root element. I've also tried capturing the "zoom" event to output the value of delineate.zoom() to the console, and it always outputs "Infinity." Any help would be greatly appreciated!

**Comment by Fuzzyma** [comment]
Give the svg a viewbox. Without viewbox you don't have any valid zoom. A sensitive default is the width and height of your svg e.g. `viewbox(0,0,width,height)`.
In case of percentage values for width and height you might want to get the width and height of the sorrounding element. At best you just use absolute values for the size of the svg too

**Comment by bptarpley** [comment]
Thank you for the incredibly fast response! Adding a viewbox with the calculated width and height of the SVG's parent element did the trick--I can now pan and zoom the image. However, whereas before the image was drawn starting at 0,0 of the SVG element, it is now positioned roughly halfway to the right of the screen. Any advice for getting the image to appear at the top left again?

```
               delineate = SVG().addTo('#delineator')
                    .size("100%", "100%")
                    .attr('id', 'svg-delineator')
                    .panZoom({panMouse: 2, zoomFactor: 0.03, zoomMin: 0.5, zoomMax: 20});
                delineate.viewbox(0, 0, $('#delineator').height(), $('#delineator').width());
                canvas = delineate.group().attr('class', 'delineator-canvas');
                image = canvas.image('img/newspaper.jpeg');
```
