### ISSUE TITLE
Can't Disable panZoom with Multiple SVGs

### ISSUE THREAD

**Issue by adleviton** [svgdotjs/svg.panzoom.js#44]
It seems that if multiple SVGs have `panZoom()` applied to them, then using` panZoom(false) `to disable multiple SVGs at once doesn't work. Any advice on this?

**Comment by Fuzzyma** [comment]
Can you create a codepen or jsfiddle to highlight the issue?

**Comment by adleviton** [comment]
As a bare bones fiddle, it seems to work as expected: https://jsfiddle.net/aleviton/63sutp8k/4/

Except that if you're in the middle of panning, `panZoom(false)` gets ignored. I'll keep investigating to see why this is not working on my end.

**Comment by adleviton** [comment]
Found it: my original issue appears after **svg.js version 2.6.6**.

I've updated my fiddle to use svg.js version 2.7.1. And after 4 seconds, pan and zoom on the SVGs does not disable as it should. However, it works in version 2.6.6: https://jsfiddle.net/aleviton/63sutp8k/6/

**Comment by Fuzzyma** [comment]
strange... your fiddle is not working though...

**Comment by adleviton** [comment]
Sorry here is the correct link with version 2.7.1, and the SVGs do not disable after 4 seconds. What you just saw was using the latest version of svg.js (but I don't have that issue when I compile on my own):

https://jsfiddle.net/aleviton/63sutp8k/8/

**Comment by Fuzzyma** [comment]
You are using panzoom 1.1.1. It should work with 1.2.3

**Comment by adleviton** [comment]
I see. I didn't realize the npm repositories were out of date. Using the latest versions of both svg.js and svg.panzoom.js, my problem is solved. Thanks. Here's my package.json in case it helps anyone else:

```
"dependencies": {
    "@svgdotjs/svg.js": "github:svgdotjs/svg.js#master",
    "@svgdotjs/svg.panzoom.js": "github:svgdotjs/svg.panzoom.js#master",
```

**Comment by Fuzzyma** [comment]
The latest 1.x version is not on npm?

**Comment by Fuzzyma** [comment]
Seems to be up to date: https://www.npmjs.com/package/svg.panzoom.js

**Comment by Fuzzyma** [comment]
>"dependencies": {
    "@svgdotjs/svg.js": "github:svgdotjs/svg.js#master",
    "@svgdotjs/svg.panzoom.js": "github:svgdotjs/svg.panzoom.js#master",

This is not how you load svg.js in version 2.x.
Just run `npm i svg.js svg.panzoom.js` to get the correct version.

In case you want to make the version jump to 3.x use `npm i @svgdotjs/svg.js @svgdotjs/svg.panzoom.js`

**Comment by adleviton** [comment]
I believe that's what I did. In any case, I ended up with the following:

![image](https://user-images.githubusercontent.com/2176348/60623110-e185f100-9daf-11e9-94fa-02d47a977047.png)

```
    "svg.js": "^2.7.1",
    "svg.panzoom.js": "^1.2.3",
```
Which is what `npm i svg.js svg.panzoom.js` installs. And that combination is what was causing my particular issue.

Thanks for the tip on installing V3 (Google is not helpful for this).

**Comment by Fuzzyma** [comment]
Hm but your fiddle was with panzoom 1.1.1 which for sure has this bug. I didnt look further in 1.2.3 because I saw it fixed there. But if you say this problem is still there I have to take a look again

**Comment by adleviton** [comment]
I have enough for now to move forward in my project. But if you want to investigate, I just updated the fiddle. This should have 2.7.1 and 1.2.3, and problem persists:

https://jsfiddle.net/aleviton/3dj286fg/6/

**Comment by Fuzzyma** [comment]
hmmm, I debugged this and have no idea why this isnt working. The removeEventListener method is called for all events with correct parameters. Strange...

**Comment by Fuzzyma** [comment]
This is fixed in svg.js v3. However, a fix for older versions is unlikely to ever happen
