### ISSUE TITLE
Question about integration

### ISSUE THREAD

**Issue by bala1979** [svgdotjs/svg.panzoom.js#50]
Can you help fix this? I am sure it has to do with how i am referencing the module.
 
![Capture](https://user-images.githubusercontent.com/5632569/69712499-edf94600-10d0-11ea-9ac6-4eb932eeada0.PNG)

**svg.panzoom.js:1 Uncaught SyntaxError: Cannot use import statement outside a module**

**Comment by Fuzzyma** [comment]
How it comes that this sort of questions end up here? Did you try googling it? The error messagge tells you, that you use an import outside a module. So you most likely used `<script src="...">` without `type=module`. But that has nothing to do with this plugin.
If you dont use modules, you can use the bundled version of this plugin to load it with the script tag: https://unpkg.com/@svgdotjs/svg.panzoom.js@2.0.3/dist/svg.panzoom.min.js

**Comment by bala1979** [comment]
My bad. I dind't see there was an option. Thanks for your help

**Comment by bala1979** [comment]
Using the wrong file
