### ISSUE TITLE
Lock Pan on an axis

### ISSUE THREAD

**Issue by guilhermelpp** [svgdotjs/svg.panzoom.js#54]
Sorry my English is not very good.
I would like to know if it is possible to lock the Pan on an axis. Example, move only on the y axis?

**Comment by Fuzzyma** [comment]
Panning is achieved through the viewox. You can catch the `panning` event and prevent it with `ev.preventDefault()`. In `ev.detail.box` you find the new viewbox. You can reset the x to what it was before and apply only the rest. However, that means you have to know the old x

**Comment by guilhermelpp** [comment]
Many thanks for the reply. I managed to do as your suggestion!
