### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by SpinoWeb** [svgdotjs/svg.panzoom.js#58]
Hello, 

when I Include the plugin after including the svg.js library in html document:
```
<script src="svg.js"></script>
<script src="svg.panzoom.js"></script>
```
I get this issue:

> Uncaught SyntaxError: Cannot use import statement outside a module (svg.panzoom.js?ver=4.9.13:1)

I'd want to use svgjs and svg.panzoom in a wordpress plugin, so I prefer to grab them by cdn

How can I fix this issue? thanks!

**Comment by SpinoWeb** [comment]
I found a solution here: https://stackoverflow.com/a/55705551
it seems to work...

**Comment by Fuzzyma** [comment]
I posted another solution as answer on stackoverflow
