### ISSUE TITLE
Set `zoomMin` to initial size?

### ISSUE THREAD

**Issue by kevindecapite** [svgdotjs/svg.panzoom.js#65]
My SVG is rendered at scale; meaning it's created with the SVG.js library with a `viewBox` of `-5 -5 1010 1010` but is resized to fit the available space via `width` and `height` attribute settings of 100% on the `<svg>` tag.

So it's possible (and common) for the SVG to render smaller than 1010 x 1010. When I zoom in and back out again, with `zoomMin` set to 1, then the SVG ends up larger than when the page first loaded (if it was originally drawn at 650 x 650, for example, then it can only be zoomed back "down" to 1010 x 1010).

There's not a reliable way to use a smaller `zoomMin` value, as the browser window could be any size when the SVG is first drawn/rendered.

Is there a way to tell `zoomMin` to use the _original_ render size as the smallest zoom factor?

**Comment by Fuzzyma** [comment]
A zoom of 1 is when the canvas size matches the viewbox size because in that case their ratio is 1. If you want to have a minimum zoom of your original zoom, just read the current zoom with `zoom()` and use that value

**Comment by kevindecapite** [comment]
Makes perfect sense and is working great... cheers!

Is there a way to read the current zoom level? I want to detect when the user has zoomed out back down to the `zoomMin` value so I can force the SVG back to its centered position.

**Comment by Fuzzyma** [comment]
You can either as mentioned use `zoom()` at the start to get the level (or on every zoom to get the current level) or (when you also need the panning), use `viewbox()` to get the viewbox you started with.

There are events you can bind to to detect when someone zoomed. See readme

**Comment by kevindecapite** [comment]
I'm understanding now, thank you again.
