### ISSUE TITLE
`oneFingerPan` option doesn't work.

### ISSUE THREAD

**Issue by kevindecapite** [svgdotjs/svg.panzoom.js#66]
I do not have `margins` set, but still I must use 2 fingers to pan on any of my mobile devices (iPhone, iPad & MS Surface).

- @svgdotjs/svg.js@3.0.16
- @svgdotjs/svg.panzoom.js@2.1.0

Refs:

- https://codepen.io/etipaced/pen/VwvLggo

**Comment by kevindecapite** [comment]
I'm not so sure about the Codepen I posted. I can't get it to _not_ work on my phone. In fact, even when I disable `oneFingerPan` by setting it to `false`, one-finger panning still operates just fine.

In my use-case, however, I cannot get one-finger panning to work at all. FYI, I do have a percentage-sized SVG (vs. pixel-defined size) so maybe that's the problem?

**Comment by Fuzzyma** [comment]
I tested it on my phone and it worked just fine. So it might have something to do with your phone since I can only test on android

**Comment by kevindecapite** [comment]
I figured out how to get the Codepen working properly on my phone. The `oneFingerPan` option does work as expected. I'm closing this as there is obviously something wrong with my specific implementation, which I'll diagnose separately.
