### ISSUE TITLE
Get Box value in zoom.

### ISSUE THREAD

**Issue by shabbir-dhangot** [svgdotjs/svg.panzoom.js#75]
I would like to calculate box.x and box.y value when I zoom-in the image. I am basically putting a dots when I click on image. When I panned on zoom level 1 I am able to place dot on perfect position. 

    this.draw.on('panning', ev => {
      this.box.x = ev.detail.box.x;
      this.box.y = ev.detail.box.y;
    });

    this.draw.on('zoom', ev => {
      console.log(ev)
      this.zoomLevel = ev.detail.level
    });

    this.image.click((ev) => {
      let tmp = [];
      tmp.push((ev.offsetX + this.box.x));
      tmp.push((ev.offsetY + this.box.y));
      let cir = this.draw.circle(10).fill('red').cx(tmp[0]).cy(tmp[1]);

How to calculate box.x and box.y when canvas is zoom.

**Comment by Fuzzyma** [comment]
You want to use the `point()` method

```js
element.on('click', (ev) => {
  const {x, y} = element.point(ev.clientX, ev.clientY)

  // do something
})
