### ISSUE TITLE
[FeatureRequest] Programmatically fit an element into the view

### ISSUE THREAD

**Issue by lucafaggianelli** [svgdotjs/svg.panzoom.js#78]
Is it possible to programmatically fit an element into the view? For _fit_ I mean zoom and pan so that an element is centered and it's zoomed as much as possible that it's still fully visible, the idea is to use the function like this:
```js
const draw = SVG()
draw.fitElement(myPath)
```

I didn't find anything in the docs, so I guess this is a feature request, if you accept it, I would be happy to work on this!

**Comment by Fuzzyma** [comment]
I was writing something else up about how this could be a different plugin but then I realized this is only one line of code :D 

```js
draw.viewbox(myPath.bbox())
```

Done! :D

**Comment by lucafaggianelli** [comment]
Ah damn I can't believe it 🤣 I wasted hours calculating aspect ratios for fitting the path 🤦 
Thanks a lot!
