### ISSUE TITLE
panStart doesn't detect mouseUp in IE

### ISSUE THREAD

**Issue by sumentse** [svgdotjs/svg.panzoom.js#8]
There seems to be an issue with panStart to detect a mouseUp event to indicate dragging has stop. I tested this on firefox and internet explorer and both doesn't work. It does however work on chrome and safari.

**Comment by Fuzzyma** [comment]
I just tested that again and I dont see a problem.
I can drag a shape and nothing bad happens. No error no nothing.

Can you create a jsfiddle so we can reproduce the problem? Otherwise I will close this in a few days

**Comment by sumentse** [comment]
https://jsfiddle.net/1x1rcvjp/

tested this on jsfiddle and still have the same issue. It just locks into the drag.

**Comment by dotnetCarpenter** [comment]
@sumentse I just tested this in FF 54.0b12 (current nightly) and it works fine. What browser versions are you using and what do you exactly do when panning with the mouse?

**Comment by dotnetCarpenter** [comment]
@sumentse or are you using a touch pad or touch screen by any chance?

**Comment by Fuzzyma** [comment]
@sumentse tested your fiddle - still no problems. <s>Which operating system are you on?</s> IE is win...

I just tried in IE and well yes - there is an issue (I tried on IE11)

**Comment by sumentse** [comment]
@dotnetCarpenter I'm using a computer and mouse. No touch pad or touch screen. 
@Fuzzyma I updated to FF 54.0b12 and it's now working. Doesn't work on FF 44. The issue appears to be isolate on Internet Explorer for Window.

**Comment by dotnetCarpenter** [comment]
What version of Internet Explorer please?

**Comment by Fuzzyma** [comment]
See above - at least in IE11

**Comment by dotnetCarpenter** [comment]
@Fuzzyma right. I guess we have to support IE11 but I feel reluctant to support older versions of IE. FF44 is definitely too old to support.

**Comment by Fuzzyma** [comment]
I agree. However it might be the same problem anyway

**Comment by dotnetCarpenter** [comment]
@Fuzzyma I don't have access to Windows. Can you investigate?

**Comment by Fuzzyma** [comment]
Yes when I have some spare time

**Comment by Fuzzyma** [comment]
@sumentse pls try again with the current master. It should work now

**Comment by sumentse** [comment]
@Fuzzyma Hey I can confirm that it works for Ie10 - 11. Thanks for investigating this issue.

**Comment by Fuzzyma** [comment]
Released in 1.0.1 - thanks for your contribution!
