### ISSUE TITLE
Get current zoom factor

### ISSUE THREAD

**Issue by cbuchert** [svgdotjs/svg.panzoom.js#81]
Hey! First off, thanks for writing this plugin! It runs well and integrates very quickly with SVG.js. It's been a pleasure to work with. Well done!

I'm trying to programmatically pan to a point in an SVG. As best as I understand, this can be accomplished like so (ripped wholesale from `readme.md`):

```javascript
// enables panZoom
var canvas = SVG()
  .addTo('#id')
  .size(1000, 1000)
  .panZoom()

// zoom programatically
canvas.zoom(lvl, point)
```

where `lvl` is the zoom level I want to use (in the case of pan it would stay current) and `point` is the point I want to center on. Getting `point` is simple. Getting `lvl` is proving a little more troublesome. Is there somewhere I can get the value for the current zoom level?

Thanks in advance!

**Comment by cbuchert** [comment]
Figured it out. Thanks!

**Comment by Fuzzyma** [comment]
Zoom will zoom INTO a point not TO a point. If you want to pan the area you have to set the viewbox so that the point is centered in the viewbox.
Glad you figured it out :)
