### ISSUE TITLE
zoom min and max level

### ISSUE THREAD

**Issue by inanisvitae** [svgdotjs/svg.panzoom.js#9]
Hi
How can I set the min and max levels for svg zoomable? Can you put min and max values as parameters in the zoom()? Thanks

**Comment by Fuzzyma** [comment]
bind to the event, prevent the default zoom when level > max and reset it to your maximum

**Comment by inanisvitae** [comment]
Hi again,
I've changed the source code a bit and created a pull request. If you like it, you can merge. Thanks
